Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 13

Metrics/AbcSize:
  Max: 28

Style/For:
  EnforcedStyle: for

AllCops:
  Exclude:
    - Gemfile
